-- Starter catalog for the shared skills taxonomy (professional profiles and
-- project requirements both draw from this table). Professionals/companies
-- can still add new skills on the fly (get-or-create); this is just a
-- reasonable seed so the autocomplete isn't empty on day one.
INSERT INTO skills (id, name, category) VALUES
    (gen_random_uuid(), 'Java', 'Sviluppo software'),
    (gen_random_uuid(), 'Spring Boot', 'Sviluppo software'),
    (gen_random_uuid(), 'JavaScript', 'Sviluppo software'),
    (gen_random_uuid(), 'React', 'Sviluppo software'),
    (gen_random_uuid(), 'Python', 'Sviluppo software'),
    (gen_random_uuid(), 'SQL', 'Sviluppo software'),
    (gen_random_uuid(), 'Docker', 'DevOps'),
    (gen_random_uuid(), 'Kubernetes', 'DevOps'),
    (gen_random_uuid(), 'AWS', 'DevOps'),
    (gen_random_uuid(), 'CI/CD', 'DevOps'),
    (gen_random_uuid(), 'Cybersecurity', 'Sicurezza'),
    (gen_random_uuid(), 'Penetration Testing', 'Sicurezza'),
    (gen_random_uuid(), 'UX Design', 'Design'),
    (gen_random_uuid(), 'UI Design', 'Design'),
    (gen_random_uuid(), 'Graphic Design', 'Design'),
    (gen_random_uuid(), 'Copywriting', 'Marketing'),
    (gen_random_uuid(), 'Marketing digitale', 'Marketing'),
    (gen_random_uuid(), 'SEO', 'Marketing'),
    (gen_random_uuid(), 'Social Media Management', 'Marketing'),
    (gen_random_uuid(), 'Project Management', 'Gestione'),
    (gen_random_uuid(), 'Agile/Scrum', 'Gestione'),
    (gen_random_uuid(), 'Business Analysis', 'Gestione'),
    (gen_random_uuid(), 'Contabilità', 'Consulenza aziendale'),
    (gen_random_uuid(), 'Consulenza fiscale', 'Consulenza aziendale'),
    (gen_random_uuid(), 'Consulenza legale', 'Consulenza aziendale'),
    (gen_random_uuid(), 'Risorse umane', 'Consulenza aziendale'),
    (gen_random_uuid(), 'Formazione aziendale', 'Formazione'),
    (gen_random_uuid(), 'Public speaking', 'Formazione'),
    (gen_random_uuid(), 'Coaching', 'Formazione'),
    (gen_random_uuid(), 'Traduzione', 'Lingue'),
    (gen_random_uuid(), 'Interpretariato', 'Lingue'),
    (gen_random_uuid(), 'Data Analysis', 'Dati'),
    (gen_random_uuid(), 'Machine Learning', 'Dati'),
    (gen_random_uuid(), 'Fotografia', 'Media'),
    (gen_random_uuid(), 'Video Editing', 'Media'),
    (gen_random_uuid(), 'Illustrazione', 'Media');
